<?php

/**
 * Created by PhpStorm.
 * User: avallac
 * Date: 09.01.16
 * Time: 4:42
 */
class PCXTest extends PHPUnit_Framework_TestCase
{
    /**
     * @dataProvider additionProvider
     */
    public function testRead($fileName, $header)
    {
        $pcx = new PCX();
        $pcx->load($fileName);
        $this->assertEquals($header, $pcx->getHeader());
    }

    public function additionProvider()
    {
        return [
            [
                'img/FISH_4.PCX',
                [
                    'ID' => 10,
                    'Version' => 2,
                    'Coding' => 1,
                    'BitPerPixel' => 4,
                    'XMin' => 0,
                    'YMin' => 0,
                    'XMax' => 1023,
                    'YMax' => 767,
                    'HRes' => 1024,
                    'VRes' => 768,
                    'Palette1' => 18,
                    'Palette2' => 13,
                    'Palette3' => 9,
                    'Palette4' => 190,
                    'Palette5' => 185,
                    'Palette6' => 23,
                    'Palette7' => 97,
                    'Palette8' => 100,
                    'Palette9' => 68,
                    'Palette10' => 178,
                    'Palette11' => 211,
                    'Palette12' => 204,
                    'Palette13' => 81,
                    'Palette14' => 74,
                    'Palette15' => 49,
                    'Palette16' => 188,
                    'Palette17' => 192,
                    'Palette18' => 144,
                    'Palette19' => 60,
                    'Palette20' => 56,
                    'Palette21' => 45,
                    'Palette22' => 126,
                    'Palette23' => 125,
                    'Palette24' => 107,
                    'Palette25' => 250,
                    'Palette26' => 229,
                    'Palette27' => 33,
                    'Palette28' => 18,
                    'Palette29' => 28,
                    'Palette30' => 86,
                    'Palette31' => 27,
                    'Palette32' => 112,
                    'Palette33' => 221,
                    'Palette34' => 242,
                    'Palette35' => 248,
                    'Palette36' => 222,
                    'Palette37' => 74,
                    'Palette38' => 78,
                    'Palette39' => 88,
                    'Palette40' => 176,
                    'Palette41' => 173,
                    'Palette42' => 106,
                    'Palette43' => 128,
                    'Palette44' => 114,
                    'Palette45' => 63,
                    'Palette46' => 44,
                    'Palette47' => 35,
                    'Palette48' => 24,
                    'Reserved' => 1,
                    'Planes' => 1,
                    'BytePerLine' => 512,
                    'PaletteInfo' => 1,
                    'HScreenSize' => 0,
                    'VScreenSize' => 0
                ],
            ], [
                'img/FISH_8.PCX',
                [
                    'ID' => 10,
                    'Version' => 5,
                    'Coding' => 1,
                    'BitPerPixel' => 8,
                    'XMin' => 0,
                    'YMin' => 0,
                    'XMax' => 1023,
                    'YMax' => 767,
                    'HRes' => 1024,
                    'VRes' => 768,
                    'Palette1' => 32,
                    'Palette2' => 1,
                    'Palette3' => 0,
                    'Palette4' => 0,
                    'Palette5' => 188,
                    'Palette6' => 241,
                    'Palette7' => 18,
                    'Palette8' => 0,
                    'Palette9' => 32,
                    'Palette10' => 233,
                    'Palette11' => 144,
                    'Palette12' => 124,
                    'Palette13' => 224,
                    'Palette14' => 1,
                    'Palette15' => 145,
                    'Palette16' => 124,
                    'Palette17' => 255,
                    'Palette18' => 255,
                    'Palette19' => 255,
                    'Palette20' => 255,
                    'Palette21' => 219,
                    'Palette22' => 1,
                    'Palette23' => 145,
                    'Palette24' => 124,
                    'Palette25' => 179,
                    'Palette26' => 22,
                    'Palette27' => 52,
                    'Palette28' => 124,
                    'Palette29' => 0,
                    'Palette30' => 0,
                    'Palette31' => 63,
                    'Palette32' => 1,
                    'Palette33' => 0,
                    'Palette34' => 0,
                    'Palette35' => 0,
                    'Palette36' => 0,
                    'Palette37' => 184,
                    'Palette38' => 22,
                    'Palette39' => 52,
                    'Palette40' => 124,
                    'Palette41' => 176,
                    'Palette42' => 243,
                    'Palette43' => 18,
                    'Palette44' => 0,
                    'Palette45' => 128,
                    'Palette46' => 193,
                    'Palette47' => 136,
                    'Palette48' => 2,
                    'Reserved' => 1,
                    'Planes' => 1,
                    'BytePerLine' => 1024,
                    'PaletteInfo' => 1,
                    'HScreenSize' => 0,
                    'VScreenSize' => 0
                ],
            ], [
                'img/FISH_24.PCX',
                [
                    'ID' => 10,
                    'Version' => 5,
                    'Coding' => 1,
                    'BitPerPixel' => 8,
                    'XMin' => 0,
                    'YMin' => 0,
                    'XMax' => 1023,
                    'YMax' => 767,
                    'HRes' => 1024,
                    'VRes' => 768,
                    'Palette1' => 32,
                    'Palette2' => 1,
                    'Palette3' => 0,
                    'Palette4' => 0,
                    'Palette5' => 188,
                    'Palette6' => 241,
                    'Palette7' => 18,
                    'Palette8' => 0,
                    'Palette9' => 32,
                    'Palette10' => 233,
                    'Palette11' => 144,
                    'Palette12' => 124,
                    'Palette13' => 224,
                    'Palette14' => 1,
                    'Palette15' => 145,
                    'Palette16' => 124,
                    'Palette17' => 255,
                    'Palette18' => 255,
                    'Palette19' => 255,
                    'Palette20' => 255,
                    'Palette21' => 219,
                    'Palette22' => 1,
                    'Palette23' => 145,
                    'Palette24' => 124,
                    'Palette25' => 179,
                    'Palette26' => 22,
                    'Palette27' => 52,
                    'Palette28' => 124,
                    'Palette29' => 0,
                    'Palette30' => 0,
                    'Palette31' => 63,
                    'Palette32' => 1,
                    'Palette33' => 0,
                    'Palette34' => 0,
                    'Palette35' => 0,
                    'Palette36' => 0,
                    'Palette37' => 184,
                    'Palette38' => 22,
                    'Palette39' => 52,
                    'Palette40' => 124,
                    'Palette41' => 176,
                    'Palette42' => 243,
                    'Palette43' => 18,
                    'Palette44' => 0,
                    'Palette45' => 104,
                    'Palette46' => 164,
                    'Palette47' => 136,
                    'Palette48' => 2,
                    'Reserved' => 1,
                    'Planes' => 3,
                    'BytePerLine' => 1024,
                    'PaletteInfo' => 1,
                    'HScreenSize' => 0,
                    'VScreenSize' => 0
                ],
            ],
        ];
    }
}